Repository typedb/typedb-dependencies, pull requests merged in 2020-10, with the labels that each got.

#205 Make maven_install fetch source JARs as well
  library/maven/rules.bzl
Labels: priority: high, type: bug, type: build

#206 Script to install Terraform
  tool/terraform/install.sh
Labels: priority: high

#203 Add RocksDB JNI dev build tool
  .grabl/automation.yml
  WORKSPACE
  distribution/deps.bzl
  library/maven/artifacts.bzl
  library/rocksdbjni/BUILD
  library/rocksdbjni/README.md
  library/rocksdbjni/RocksDbBuilder.kt
  library/rocksdbjni/VERSION
Labels: priority: medium, type: build

#208 Allow hashbangs at the start of Checkstyle targets
  tool/checkstyle/config/checkstyle-file-header-agpl.txt
  tool/checkstyle/config/checkstyle-file-header-apache.txt
  tool/checkstyle/config/checkstyle-file-header-grakn-kgms.txt
  tool/checkstyle/templates/checkstyle.xml
Labels: priority: medium, type: build

#213 Remove hard-coded Java path
  library/rocksdbjni/BUILD
  library/rocksdbjni/RocksDbBuilder.kt
Labels: type: bug
