Repository typedb/typedb-dependencies, pull requests merged in 2020-11, with the labels that each got.

#215 Add Google OR-Tools builder for Linux and Windows
  WORKSPACE
  library/maven/artifacts.bzl
  library/ortools/BUILD
  library/ortools/Deploy.kt
  library/ortools/Deploy.template.kt
  library/ortools/archive-exports-files
  library/ortools/deps.bzl
Labels: type: feature

#217 Add native_java_libraries and host_compatible_java_library
  builder/java/rules.bzl
Labels: priority: high, type: build

#218 Update jline version
  library/maven/artifacts.bzl
Labels: type: build

#220 Add tooling for importing platform-specific artifacts
  builder/java/rules.bzl
  distribution/artifact/rules.bzl
  library/ortools/BUILD
  library/ortools/deps.bzl
  util/platform/BUILD
Labels: priority: medium, type: refactor

#223 Downgrade GRPC
  library/maven/artifacts.bzl
Labels: type: build

#225 Make RBE script portable (to support CentOS)
  tool/bazelinstall/rbe.sh
Labels: priority: blocker, type: bug, type: build

#224 Upgrade gRPC to 1.33, Netty to 4.1.51
  library/maven/artifacts.bzl
Labels: priority: high, type: build
