Repository typedb/typedb-dependencies, pull requests merged in 2020-08, with the labels that each got.

#164 Add jeromq maven dependency.
  library/maven/artifacts.bzl
Labels: priority: high, type: build

#166 Update our maven repository URLs
  library/maven/rules.bzl
Labels: priority: high, type: bug

#174 Implement release-validate-deps with kotlin
  WORKSPACE
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/maven/artifacts/com/google/protobuf/BUILD
  dependencies/maven/update.sh
  library/maven/artifacts.bzl
  tool/release/BUILD
  tool/release/ValidateDeps.kt
  tool/release/rules.bzl
  tool/release/validate-deps.py
Labels: priority: high, type: refactor

#175 Use bazel-distribution for `assemble-maven`
  WORKSPACE
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  distribution/deployment.properties
  distribution/deps.bzl
  distribution/maven/rules.bzl
  library/maven/artifacts.bzl
  library/maven/rules.bzl
Labels: priority: high, type: build, type: refactor

#177 Restore pyenv cloning in tools/bazelinstall/rbe.sh
  tool/bazelinstall/rbe.sh
Labels: type: bug, type: build

#179 Fix path in tool/bazelrun/rbe.py
  tool/bazelrun/rbe.py
  tool/bazelrun/rbe.sh
Labels: type: bug, type: build

#182 Update rules_nodejs
  WORKSPACE
  builder/nodejs/deps.bzl
  dependencies/graknlabs/repositories.bzl
  distribution/apt/BUILD
Labels: priority: high, type: build

#180 Remove releasability, move 'artifact' rules to 'bazel-distribution', move 'grakn-bin' to 'common'
  .circleci/config.yml
  BUILD
  VERSION
  WORKSPACE
  binary/BUILD
  binary/grakn
  binary/grakn-docker.sh
  binary/grakn.bat
  dependencies/graknlabs/repositories.bzl
  deployment.properties
  distribution/BUILD
  distribution/apt/BUILD
  distribution/artifact/rules.bzl
  distribution/artifact/templates/BUILD
  distribution/artifact/templates/deploy.py
  distribution/deployment.bzl
  distribution/deployment.properties
  distribution/deps.bzl
  distribution/rpm/BUILD
  distribution/rpm/grakn-bin.spec
  tool/release/BUILD
  tool/release/rules.bzl
Labels: priority: high, type: build

#188 Bazel distribution bump dependencies for assemble-npm bug fix
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#186 Extends artifact_extractor to support zip decompression
  distribution/artifact/rules.bzl
Labels: type: build

#190 Makes artifact-extractor agnostic to the OS it runs on
  distribution/artifact/rules.bzl
Labels: type: build

#191 Makes artifact-extractor support bash and cmd executors
  distribution/artifact/rules.bzl
Labels: type: build
