Repository typedb/typedb-dependencies, pull requests merged in 2020-07, with the labels that each got.

#148 Integrate support for BuildBuddy
  .bazelversion
  tool/bazelinstall/linux.sh
  tool/bazelinstall/mac.sh
  tool/bazelinstall/rbe.sh
  tool/bazelrun/rbe.py
Labels: priority: high, type: build

#150 Update deps.bzl
  distribution/deps.bzl
Labels: priority: blocker, type: build

#151 Add artifact rules (moved from bazel-distribution)
  distribution/artifact/BUILD
  distribution/artifact/rules.bzl
  distribution/artifact/templates/BUILD
  distribution/artifact/templates/deploy.py
  distribution/deployment.properties
Labels: priority: high, type: build

#154 Add version interpolation to artifact rules
  distribution/artifact/rules.bzl
  distribution/artifact/templates/deploy.py
Labels: priority: high, type: build

#156 Add extract script generation macro
  distribution/artifact/rules.bzl
Labels: priority: blocker, type: build, type: feature

#155 Add dependencies needed for building Grabl
  library/maven/artifacts.bzl
Labels: type: build

#160 Change extract artifact to executable rule
  distribution/artifact/rules.bzl
Labels: priority: high, type: build

#162 Add JMH benchmarking library and rules
  library/jmh/BUILD
  library/jmh/artifacts.bzl
  library/jmh/rules.bzl
  library/maven/artifacts.bzl
Labels: priority: blocker, type: feature

#163 Update to use with 2.0 and private artifact repository
  binary/grakn
  distribution/artifact/BUILD
  distribution/artifact/create-netrc.sh
  distribution/artifact/rules.bzl
Labels: priority: high, type: build
