Repository typedb/typedb-dependencies, pull requests merged in 2020-06, with the labels that each got.

#137 Use new machine image in CI
  .circleci/config.yml
  ci/install-bazel-rbe.sh
Labels: priority: medium, type: build, type: refactor

#138 Buildbarn setup
  .gitignore
  ci/buildbarn/README.md
  ci/buildbarn/main.tf
  ci/buildbarn/setup-buildbarn.sh
Labels: priority: high, type: build

#139 Add distribution repo settings
  deployment.properties
  distribution/deps.bzl
Labels: priority: blocker

#142 Remove BuildBarn setup from @graknlabs_dependencies
  .gitignore
  tool/misc/buildbarn/README.md
  tool/misc/buildbarn/main.tf
  tool/misc/buildbarn/setup-buildbarn.sh
Labels: priority: high, type: build

#145 Add Picocli maven dependency
  library/maven/artifacts.bzl
Labels: priority: high, type: build
