Repository typedb/typedb-dependencies, pull requests merged in 2020-12, with the labels that each got.

#229 Don't subject node_modules to checkstyle:test-coverage
  tool/checkstyle/test-coverage.py
Labels: priority: medium, type: build

#230 DependencyAnalysis: update dependency filename
  grabl/analysis/DependencyAnalysis.kt
Labels: priority: high, type: bug, type: build

#231 Fix dependency-analyis false-negative results
  grabl/analysis/DependencyAnalysis.kt
Labels: priority: blocker, type: bug, type: build

#232 Fix dependency-analysis for good
  grabl/analysis/DependencyAnalysis.kt
Labels: priority: high, type: bug

#234 Pull in graknlabs_grakn_core artifact for Windows
  distribution/artifact/rules.bzl
Labels: priority: high, type: feature

#236 Build remotely on Ubuntu 20.04
  .bazelrc
  .grabl/automation.yml
Labels: priority: high, type: build

#237 Implement //tool/release:bump
  tool/common/deps.bzl
  tool/release/BUILD
  tool/release/Bump.kt
Labels: priority: high, type: build, type: feature

#238 Rename grakn-kgms to commercial in checkstyle_test
  tool/checkstyle/config/BUILD
  tool/checkstyle/config/checkstyle-file-header-commercial.txt
  tool/checkstyle/rules.bzl
Labels: type: build, type: refactor

#239 Implement release_validate_nodejs_deps
  tool/release/BUILD
  tool/release/ValidateNodeJsDeps.kt
  tool/release/rules.bzl
Labels: priority: high, type: build, type: feature

#240 Fix tool/bazelinstall/mac.sh
  tool/bazelinstall/mac.sh
Labels: priority: blocker, type: bug, type: build

#241 Upgrade @graknlabs_bazel_distribution
  distribution/deps.bzl
Labels: priority: high, type: build

#245 Ease operations with repo.grakn.ai
  tool/misc/BUILD
  tool/misc/restart-repo-container.sh
  tool/misc/ssh-repo-container.sh
  tool/misc/ssh-repo-machine.sh
Labels: priority: high, type: build
