Repository typedb/typedb-dependencies, pull requests merged in 2021-01, with the labels that each got.

#246 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#247 Change web-dev to web-docs
  tool/release/docs.py
Labels: priority: high, type: build, type: refactor

#248 Bump year in license headers to 2021
  BUILD
  WORKSPACE
  builder/bazel/BUILD
  builder/bazel/deps.bzl
  builder/grpc/BUILD
  builder/grpc/deps.bzl
  distribution/BUILD
  distribution/deployment.bzl
  distribution/deps.bzl
  distribution/rpm/BUILD
  image/buildbuddy/BUILD
  image/rbe/BUILD
  library/maven/BUILD
  library/rocksdbjni/BUILD
  tool/BUILD
  tool/bazelrun/rbe.py
  tool/cache/cache.py
  tool/checkstyle/BUILD
  tool/checkstyle/deps.bzl
  tool/checkstyle/rules.bzl
  tool/checkstyle/templates/checkstyle.xml
  tool/checkstyle/test-coverage.py
  tool/common/BUILD
  tool/jmh/BUILD
  tool/jmh/rules.bzl
  tool/misc/BUILD
  tool/release/BUILD
  tool/release/bump-version.py
  tool/release/rules.bzl
  tool/sonarcloud/BUILD
  tool/sonarcloud/code-analysis.py
  tool/sonarcloud/deps.bzl
  tool/unuseddeps/deps.bzl
Labels: type: bug

#250 Allow using incomplete labels in host_compatible_java_test and native_java_library
  builder/java/rules.bzl
Labels: type: bug, type: build

#251 Fix console warnings caused by out of date dependency
  library/maven/artifacts.bzl
Labels: type: bug

#252 Fix release_validate_python_deps
  distribution/deps.bzl
  tool/release/ValidatePythonDeps.kt
Labels: priority: high, type: bug

#254 Update bazel-distribution
  distribution/deps.bzl
Labels: priority: high, type: build
