Repository typedb/typedb-dependencies, pull requests merged in 2021-05, with the labels that each got.

#281 Upgrade @rules_docker to our fork
  distribution/docker/bazelbuild-rules-docker-fix-tarfile-format.patch
  distribution/docker/deps.bzl
Labels: priority: high, type: bug, type: build

#283 Introduce a tool to rewrite ANTLR grammars
  builder/antlr/BUILD
  builder/antlr/GrammarAdapter.kt
  builder/antlr/deps.bzl
  builder/antlr/rules.bzl
  tool/common/deps.bzl
Labels: priority: high, type: feature

#288 Bump pygithub to 1.55
  tool/requirements.txt
Labels: priority: blocker, type: build

#291 Add npm private repo
  distribution/deployment.bzl
Labels: priority: medium, type: build
