Repository typedb/typedb-dependencies, pull requests merged in 2021-12, with the labels that each got.

#328 Add Jetpack Compose and JVM platform image assembly deps
  builder/compose/deps.bzl
  builder/kotlin/deps.bzl
  distribution/deps.bzl
  library/maven/artifacts.bzl
Labels: type: feature, priority: high

#329 Update bazel-distribution
  distribution/deps.bzl
Labels: type: build, priority: high

#330 Upgrade to latest bazel-distribution
  distribution/deps.bzl
Labels: type: build, priority: high

#331 Update //library/crates
  distribution/deps.bzl
  library/crates/remote/BUILD.antlr-rust-0.2.0.bazel
  library/crates/remote/BUILD.better_any-0.1.1.bazel
  library/crates/remote/BUILD.better_typeid_derive-0.1.1.bazel
  library/crates/remote/BUILD.bit-set-0.5.2.bazel
  library/crates/remote/BUILD.bit-vec-0.6.3.bazel
  library/crates/remote/BUILD.bitflags-1.3.2.bazel
  library/crates/remote/BUILD.byteorder-1.4.3.bazel
  library/crates/remote/BUILD.cfg-if-1.0.0.bazel
  library/crates/remote/BUILD.instant-0.1.12.bazel
  library/crates/remote/BUILD.lazy_static-1.4.0.bazel
  library/crates/remote/BUILD.libc-0.2.106.bazel
  library/crates/remote/BUILD.lock_api-0.4.5.bazel
  library/crates/remote/BUILD.murmur3-0.4.1.bazel
  library/crates/remote/BUILD.once_cell-1.8.0.bazel
  library/crates/remote/BUILD.parking_lot-0.11.2.bazel
  library/crates/remote/BUILD.parking_lot_core-0.8.5.bazel
  library/crates/remote/BUILD.proc-macro2-1.0.32.bazel
  library/crates/remote/BUILD.quote-1.0.10.bazel
  library/crates/remote/BUILD.redox_syscall-0.2.10.bazel
  library/crates/remote/BUILD.scopeguard-1.1.0.bazel
  library/crates/remote/BUILD.smallvec-1.7.0.bazel
  library/crates/remote/BUILD.syn-1.0.81.bazel
  library/crates/remote/BUILD.typed-arena-2.0.1.bazel
  library/crates/remote/BUILD.unicode-xid-0.2.2.bazel
  library/crates/remote/BUILD.uuid-0.8.2.bazel
  library/crates/remote/BUILD.winapi-0.3.9.bazel
  library/crates/remote/BUILD.winapi-i686-pc-windows-gnu-0.4.0.bazel
  library/crates/remote/BUILD.winapi-x86_64-pc-windows-gnu-0.4.0.bazel
Labels: type: build

#333 Bump @vaticle_bazel_distribution
  distribution/deps.bzl
Labels: type: bug

#336 Update linux RocksDBJNI builder
  library/rocksdbjni/BUILD
  library/rocksdbjni/BuilderLinux.kt
  library/rocksdbjni/BuilderMac.kt
  library/rocksdbjni/README.md
Labels: priority: medium

#337 Update logging and Antlr4 dependencies
  library/maven/artifacts.bzl
Labels: type: build, priority: high

#339 Upgrade grpc to 1.43.0 and netty to 4.1.61.Final
  library/maven/artifacts.bzl
Labels: type: build, priority: high

#340 Update create-notes to escape notes and use time-ordering
  tool/release/createnotes/CreateNotes.kt
  tool/release/createnotes/Note.kt
Labels: type: bug, priority: blocker
