Repository typedb/typedb-dependencies, pull requests merged in 2021-08, with the labels that each got.

#299 Upgrade Kotlin to 1.5 and support Compose
  builder/compose/BUILD
  builder/compose/deps.bzl
  builder/java/rules.bzl
  builder/kotlin/deps.bzl
  library/maven/artifacts.bzl
  library/maven/rules.bzl
  library/ortools/deploy/Deploy.template.kt
Labels: type: feature, priority: high

#302 Bump versions of Azure Storage Maven libraries
  library/maven/artifacts.bzl
Labels: type: build, priority: blocker, dependencies

#303 Integrate libraries to support logging to Logstash
  library/maven/artifacts.bzl
Labels: type: build, priority: high

#304 Add rules_rust to allow building Rust code
  builder/rust/BUILD
  builder/rust/deps.bzl
Labels: type: build, priority: high
