Repository typedb/typedb-dependencies, pull requests merged in 2022-11, with the labels that each got.

#375 Rust IDE sync tool
  ide/rust/BUILD
  ide/rust/RepoCargoManifestGenerator.kt
  ide/rust/Syncer.kt
  ide/rust/sync_info_aspect.bzl
  tool/common/deps.bzl
Labels: type: feature, priority: high

#378 Fix IDE sync tool generating binary names that are illegal in Cargo.toml
  ide/rust/BUILD
  ide/rust/RepoCargoManifestGenerator.kt
Labels: type: bug, priority: medium

#381 Delete 'grpc' and 'protobuf' crates
  library/crates/BUILD.bazel
  library/crates/Cargo.toml
  library/crates/crates.bzl
  library/crates/remote/BUILD.base64-0.9.3.bazel
  library/crates/remote/BUILD.bytes-0.5.6.bazel
  library/crates/remote/BUILD.cloudabi-0.0.3.bazel
  library/crates/remote/BUILD.fuchsia-cprng-0.1.1.bazel
  library/crates/remote/BUILD.fuchsia-zircon-0.3.3.bazel
  library/crates/remote/BUILD.fuchsia-zircon-sys-0.3.3.bazel
  library/crates/remote/BUILD.grpc-0.8.3.bazel
  library/crates/remote/BUILD.grpc-compiler-0.8.3.bazel
  library/crates/remote/BUILD.grpc-protobuf-0.8.3.bazel
  library/crates/remote/BUILD.httpbis-0.9.1.bazel
  library/crates/remote/BUILD.iovec-0.1.4.bazel
  library/crates/remote/BUILD.kernel32-sys-0.2.2.bazel
  library/crates/remote/BUILD.lazy_static-1.4.0.bazel
  library/crates/remote/BUILD.log-0.4.8.bazel
  library/crates/remote/BUILD.log-ndc-0.2.0.bazel
  library/crates/remote/BUILD.mio-0.6.23.bazel
  library/crates/remote/BUILD.mio-uds-0.6.8.bazel
  library/crates/remote/BUILD.miow-0.2.2.bazel
  library/crates/remote/BUILD.net2-0.2.37.bazel
  library/crates/remote/BUILD.pin-project-lite-0.1.12.bazel
  library/crates/remote/BUILD.protobuf-2.18.2.bazel
  library/crates/remote/BUILD.protobuf-codegen-2.18.2.bazel
  library/crates/remote/BUILD.protoc-2.18.2.bazel
  library/crates/remote/BUILD.protoc-rust-2.18.2.bazel
  library/crates/remote/BUILD.protoc-rust-grpc-0.8.3.bazel
  library/crates/remote/BUILD.rand-0.4.6.bazel
  library/crates/remote/BUILD.rand-0.5.6.bazel
  library/crates/remote/BUILD.rand_core-0.3.1.bazel
  library/crates/remote/BUILD.rand_core-0.4.2.bazel
  library/crates/remote/BUILD.rdrand-0.4.0.bazel
  library/crates/remote/BUILD.safemem-0.3.3.bazel
  library/crates/remote/BUILD.tempdir-0.3.7.bazel
  library/crates/remote/BUILD.tls-api-0.4.0.bazel
  library/crates/remote/BUILD.tls-api-stub-0.4.0.bazel
  library/crates/remote/BUILD.tokio-0.2.25.bazel
  library/crates/remote/BUILD.unix_socket-0.5.0.bazel
  library/crates/remote/BUILD.void-1.0.2.bazel
  library/crates/remote/BUILD.winapi-0.2.8.bazel
  library/crates/remote/BUILD.winapi-0.3.9.bazel
  library/crates/remote/BUILD.winapi-build-0.1.1.bazel
  library/crates/remote/BUILD.ws2_32-sys-0.2.1.bazel
Labels: type: refactor, priority: medium

#383 Update bazel-distribution
  distribution/deps.bzl
Labels: type: refactor, priority: medium

#384 Exclude all rocksdbjni targets from build
  library/rocksdbjni/BUILD
Labels: type: refactor, priority: high

#390 Exclude 'target' and '.DS_Store' from checkstyle coverage
  tool/checkstyle/test-coverage.py
Labels: type: bug, priority: medium

#391 Add `rust_tonic_compile` rule
  WORKSPACE
  builder/grpc/rust/BUILD
  builder/grpc/rust/compile.bzl
  builder/grpc/rust/compile.rs
Labels: type: feature, priority: high

#392 Update bazel-distribution
  .factory/automation.yml
  distribution/deps.bzl
Labels: type: refactor, priority: high

#395 Add regex crate
  library/crates/BUILD.bazel
  library/crates/Cargo.toml
Labels: priority: high, dependencies

#396 Add pest crate to cargo raze
  library/crates/BUILD.bazel
  library/crates/Cargo.toml
  library/crates/crates.bzl
  library/crates/remote/BUILD.alcoholic_jwt-4091.0.0.bazel
  library/crates/remote/BUILD.antlr-rust-0.3.0-beta.bazel
  library/crates/remote/BUILD.murmur3-0.4.1.bazel
  library/crates/remote/BUILD.native-tls-0.2.11.bazel
  library/crates/remote/BUILD.openssl-0.10.43.bazel
  library/crates/remote/BUILD.openssl-sys-0.9.77.bazel
  library/crates/remote/BUILD.openssl-sys-0.9.78.bazel
  library/crates/remote/BUILD.pest-2.4.1.bazel
  library/crates/remote/BUILD.pest_derive-2.4.1.bazel
  library/crates/remote/BUILD.pest_generator-2.4.1.bazel
  library/crates/remote/BUILD.pest_meta-2.4.1.bazel
  library/crates/remote/BUILD.sha1-0.10.5.bazel
  library/crates/remote/BUILD.smallvec-1.9.0.bazel
  library/crates/remote/BUILD.typed-arena-2.0.1.bazel
  library/crates/remote/BUILD.ucd-trie-0.1.5.bazel
  library/crates/remote/BUILD.winapi-0.3.9.bazel
Labels: priority: high

#397 IDE sync: generate correct paths for transitive Vaticle deps
  .gitignore
  ide/rust/RepoCargoManifestGenerator.kt
  ide/rust/Syncer.kt
Labels: type: bug, priority: high

#398 IDE sync: generate correct paths for crates containing generated sources
  ide/rust/RepoCargoManifestGenerator.kt
  ide/rust/sync_info_aspect.bzl
Labels: type: bug, priority: high

#399 Add itertools crate to cargo raze
  library/crates/BUILD.bazel
  library/crates/Cargo.toml
Labels: priority: high, dependencies

#400 Rust IDE sync: compile generated sources
  ide/rust/RepoCargoManifestGenerator.kt
  ide/rust/Syncer.kt
  ide/rust/sync_info_aspect.bzl
Labels: type: bug, priority: high
