Repository typedb/typedb-dependencies, pull requests merged in 2023-07, with the labels that each got.

#452 Update Bazel to 6.2.0 and remove bazel install scripts
  .bazelversion
  tool/bazelinstall/BUILD
  tool/bazelinstall/linux.sh
  tool/bazelinstall/mac.sh
Labels: type: refactor, priority: blocker

#456 SWIG rules fixes
  builder/swig/java.bzl
Labels: type: bug, priority: high

#455 Update jvm_rules_external and Netty ssl dependencies
  builder/java/deps.bzl
  library/maven/artifacts.bzl
Labels: dependencies
