Repository typedb/typedb-dependencies, pull requests merged in 2023-02, with the labels that each got.

#418 Avoid depending on commit-based archives
  builder/java/deps.bzl
  distribution/deps.bzl
  distribution/helm/deps.bzl
Labels: type: refactor, priority: medium

#422 Generify IDE sync tool into Cargo sync tool
  ide/rust/RepoCargoManifestGenerator.kt
  ide/rust/Syncer.kt
  tool/cargo/BUILD
  tool/cargo/Syncer.kt
  tool/cargo/sync_properties_aspect.bzl
Labels: type: build, priority: high

#423 TypeDB Client Rust dependencies: async runtimes, tokio-stream
  .gitignore
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: dependencies

#425 Section off cargo dev dependenciess
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: refactor, priority: medium
