Repository typedb/typedb-dependencies, pull requests merged in 2023-09, with the labels that each got.

#466 Upgrade speedb to 2.6.0
  library/maven/artifacts.bzl
Labels: type: feature, dependencies

#464 Allow linking SWIG Python for different platforms
  WORKSPACE
  builder/rust/deps.bzl
  builder/rust/rules.bzl
  builder/swig/python.bzl
  distribution/deps.bzl
  library/crates/crates.bzl
  tool/swig/deps.bzl
  util/platform/BUILD
Labels: type: feature, priority: blocker

#461 Bump logback & slf4j dependencies for audit logging
  library/maven/artifacts.bzl
Labels: type: feature, dependencies

#470 Upgrade helm bazel rules
  distribution/helm/deps.bzl
Labels: type: build, priority: blocker, dependencies

#473 Add arm64 skiko dependencies for TypeDB-Studio
  library/maven/artifacts.bzl
  util/platform/BUILD
  util/platform/constraints.bzl
Labels: type: build, priority: blocker, dependencies

#474 Remove stray win_arm64 reference
  util/platform/BUILD
Labels: type: bug, type: build

#475 Java native artifact rules update to reflect CPU architecture
  builder/compose/deps.bzl
  builder/java/rules.bzl
  builder/rust/rules.bzl
  builder/swig/java.bzl
  builder/swig/python.bzl
  distribution/artifact/rules.bzl
  distribution/deps.bzl
  library/ortools/deps.bzl
  library/ortools/rust/BUILD
  util/platform/BUILD
  util/platform/constraints.bzl
Labels: type: feature, priority: blocker
