Repository typedb/typedb-dependencies, pull requests merged in 2023-01, with the labels that each got.

#411 Don't use Bazel in crate-universe lockfile update script
  .gitignore
  library/crates/Cargo.lock
  library/crates/update.sh
Labels: type: bug, priority: high

#413 Improve crate name detection in Rust IDE sync
  distribution/deps.bzl
  ide/rust/sync_info_aspect.bzl
Labels: type: bug, priority: high

#415 Bump netty dependency versions
  library/maven/artifacts.bzl
Labels: type: build, priority: high, dependencies

#414 TypeDB Cloud server logging dependencies
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: high, dependencies
