Repository typedb/typedb-dependencies, pull requests merged in 2023-08, with the labels that each got.

#459 Add explicit jNaCl dependency for ZeroMQ key verification
  library/maven/artifacts.bzl
Labels: dependencies

#460 Introduce SWIG Python rules
  WORKSPACE
  builder/python/deps.bzl
  builder/swig/python.bzl
  distribution/deps.bzl
  tool/common/deps.bzl
  tool/requirements.txt
Labels: type: feature, priority: high, dependencies

#462 Fix target label check in the cargo project generation
  builder/rust/cargo/project_aspect.bzl
Labels: type: bug, priority: blocker

#463 Add tokio-retry crate
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: feature, priority: high

#465 Upgrade NodeJS dependencies: migrate to rules_js & rules_ts, upgrade gRPC & protobuf
  builder/grpc/deps.bzl
  builder/java/deps.bzl
  builder/nodejs/deps.bzl
  library/maven/artifacts.bzl
  library/maven/rules.bzl
Labels: priority: blocker, dependencies
