Repository typedb/typedb-dependencies, pull requests merged in 2023-11, with the labels that each got.

#483 Pin JDK 17 versions and URLs
  builder/compose/deps.bzl
Labels: type: build, priority: blocker, dependencies

#484 Switch to our patched version of rules_rust (based off v0.30.0)
  builder/rust/deps.bzl
  library/crates/crates.bzl
Labels: type: build, type: feature, priority: high

#485 Disable non-camel-case warnings in tonic compile
  builder/grpc/rust/compile.rs
Labels: type: refactor, priority: medium

#486 Add env_logger crate dependency
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: feature, priority: high

#482 Enable native TLS roots feature on tonic
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: feature, priority: high, dependencies
