Repository typedb/typedb-dependencies, pull requests merged in 2023-06, with the labels that each got.

#446 Replace RocksDB dependency with SpeeDB
  library/maven/artifacts.bzl
  library/rocksdbjni/BUILD
  library/rocksdbjni/BuilderLinux.kt
  library/rocksdbjni/BuilderMac.kt
  library/rocksdbjni/Common.kt
  library/rocksdbjni/README.md
  library/rocksdbjni/VERSION
Labels: type: build, priority: high, dependencies

#448 Upgrade ORTools dependencies to include Mac and Linux ARM
  distribution/deps.bzl
  library/maven/artifacts.bzl
Labels: type: build, type: refactor, dependencies

#449 Add maybe-async crate dependency
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: high, dependencies

#450 Allow extra SWIG includes and extra args
  builder/swig/java.bzl
Labels: type: feature, priority: high
