Repository typedb/typedb-dependencies, pull requests merged in 2023-10, with the labels that each got.

#476 Update pest 2.4.0 => 2.7.4
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: blocker, dependencies

#478 Fix checkstyle coverage check for filenames with whitespaces
  tool/checkstyle/test-coverage.py
Labels: type: bug, priority: high

#477 Dependencies for docs generation
  library/maven/artifacts.bzl
  tool/common/deps.bzl
  tool/docs/BUILD
  tool/docs/java_deps.bzl
  tool/docs/python_deps.bzl
  tool/docs/requirements.txt
Labels: type: feature, priority: high

#480 Add jsonwebtoken crate
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: feature, priority: high

#479 Introduce dependencies and rules for C and C++
  builder/cpp/BUILD
  builder/cpp/deps.bzl
Labels: type: build, priority: blocker, dependencies
