Repository typedb/typedb-dependencies, pull requests merged in 2024-05, with the labels that each got.

#532 Add same-file crate dependency
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: dependencies

#536 Bump snake-yaml maven dependency to 2.2
  library/maven/artifacts.bzl
Labels: type: bug

#535 Add dependencies for Ktor server content negotiation based on jackson
  library/maven/artifacts.bzl
Labels: priority: high, dependencies

#537 Update sync dependencies to point to bot.typedb.com
  tool/sync/dependencies.py
Labels: type: refactor, priority: low

#543 Add mockito-kotlin dependency
  library/maven/artifacts.bzl
Labels: priority: high, dependencies

#538 Update chrono to 0.4.38 to avoid depending on deprecated functionality
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: high, dependencies
