Repository typedb/typedb-dependencies, pull requests merged in 2024-01, with the labels that each got.

#492 Improve clarity of protobuf/grpc builder
  builder/proto_grpc/BUILD
  builder/proto_grpc/deps.bzl
  builder/proto_grpc/rust/BUILD
  builder/proto_grpc/rust/compile.bzl
  builder/proto_grpc/rust/compile.rs
Labels: type: refactor, priority: high

#494 Update target label moved from grpc to proto_grpc
  builder/proto_grpc/rust/compile.bzl
Labels: type: bug, priority: blocker

#491 Move docs generation to bazel-distribution repository
  distribution/deps.bzl
  tool/docs/BUILD
  tool/docs/java_deps.bzl
  tool/docs/python_deps.bzl
  tool/docs/requirements.txt
Labels: type: refactor

#493 Migrate artifact hosting to cloudsmith
  WORKSPACE
  builder/compose/deps.bzl
  builder/rust/deps.bzl
  distribution/artifact/create-netrc.sh
  distribution/artifact/rules.bzl
  distribution/deployment.bzl
  distribution/deps.bzl
  distribution/rpm/BUILD
  distribution/rpm/release.repo
  distribution/rpm/snapshot.repo
  library/crates/update.sh
  library/maven/rules.bzl
  library/ortools/java/BUILD
  library/ortools/java/Deploy.template.kt
  library/ortools/java/deps.bzl
  tool/unuseddeps/deps.bzl
Labels: type: build

#495 Add Ktor Kotlin web framework
  library/maven/artifacts.bzl
Labels: type: feature, priority: blocker

#497 Merge TypeDB Platform upgrade branch
  library/crates/Cargo.lock
  library/crates/Cargo.toml
  library/maven/artifacts.bzl
Labels: type: feature, priority: blocker, dependencies

#500 Add Firebase Admin Maven artifact
  library/maven/artifacts.bzl
Labels: priority: blocker, dependencies

#501 Upgrade rules_kotlin and Jetbrains Compose
  builder/kotlin/deps.bzl
  library/maven/artifacts.bzl
Labels: priority: high
