Repository typedb/typedb-dependencies, pull requests merged in 2024-02, with the labels that each got.

#502 Stripe Java and Ktor JSON dependencies
  library/maven/artifacts.bzl
Labels: priority: high, dependencies

#503 Release notes generator: RC support and ignore prereleases to generate changelog since previous release
  tool/release/notes/Commit.kt
  tool/release/notes/Note.kt
  tool/release/notes/Version.kt
Labels: type: feature, priority: blocker

#504 Add OutputGroupInfo to cbindgen rule
  builder/rust/rules.bzl
Labels: dependencies

#507 Upgrade rules_kotlin and Jetbrains Compose
  builder/kotlin/deps.bzl
  library/maven/artifacts.bzl
Labels: priority: high, dependencies

#508 Bump mailgun java dependency
  library/maven/artifacts.bzl
Labels: type: feature, priority: high, dependencies
