Repository typedb/typedb-dependencies, pull requests merged in 2024-04, with the labels that each got.

#517 Update cucumber BDD dependencies for C++
  builder/cpp/deps.bzl
Labels: type: build

#522 Update JSON dependency used by C++ cucumber BDD
  builder/cpp/deps.bzl
Labels: dependencies

#525 Add macro rules attribute crate
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: high, dependencies

#524 Open PR tool
  tool/common/deps.bzl
  tool/github/BUILD
  tool/github/OpenPR.kt
Labels: type: feature, priority: high

#520 Add support for multiple names of version file in version bump tool
  library/maven/artifacts.bzl
  tool/common/deps.bzl
  tool/github/OpenPR.kt
  tool/release/version/BUILD
  tool/release/version/Bump.kt
Labels: type: feature, priority: high
