Repository typedb/typedb-dependencies, pull requests merged in 2024-03, with the labels that each got.

#512 Add Kubernetes Client Maven Artifact
  library/maven/artifacts.bzl
Labels: type: feature, priority: blocker

#506 Ensure releases don't depend on RC
  tool/release/deps/ValidateDeps.kt
  tool/release/deps/ValidateNodeJsDeps.kt
  tool/release/deps/ValidatePythonDeps.kt
  tool/release/deps/rules.bzl
Labels: type: bug, priority: high

#513 Add lz4 crate dependency
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: type: feature, priority: blocker, dependencies

#514 Add pprof for rust benchmarking flame graphs
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: dependencies

#515 Dependencies update for C# driver.
  builder/csharp/BUILD
  builder/csharp/deps.bzl
  builder/swig/csharp.bzl
Labels: status: blocked, dependencies
