Repository typedb/typedb-dependencies, pull requests merged in 2025-03, with the labels that each got.

#568 Add unicase to crate dependencies.
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: dependencies

#570 Update dependencies for 3.1.0
  library/crates/Cargo.lock
  library/crates/Cargo.toml
Labels: priority: high, dependencies

#571 Merge crate properties by path
  tool/ide/RustManifestSyncer.kt
Labels: type: bug, priority: medium
